blog/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.blog, name='Blog'),
    path('categoria/<int:categoria_id>/' ,views.categoria, name='Categoria'),
    path('post/<int:id>/',views.post, name='Post'),
]

carro/urls.py
from django.urls import path
from . import views

app_name='carro'

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_producto, name='limpiar'),
  
]

proyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('', include('proyectoWebApp.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autenticacion.urls')),

]

tienda/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.tienda, name='Tienda'),
    path('categoriaProd/<int:categoria_id>/' ,views.categoriaProd, name='CategoriaProd'),
]

tienda/models.py
from xml.etree.ElementInclude import default_loader
from django.db import models


# Create your models here.

class CategoriaProducto(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    

    class Meta:
        verbose_name='categoriaProducto'
        verbose_name_plural='categoriasProductos'

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre=models.CharField(max_length=50)
    marca=models.CharField(max_length=50)
    descripcion=models.CharField(max_length=250, blank=True)
    imagen=models.ImageField(upload_to="tienda")
    precio=models.FloatField()
    disponibilidad=models.BooleanField()
    categoriasProd=models.ManyToManyField(CategoriaProducto)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)


    class Meta:
        verbose_name='producto'
        verbose_name_plural='productos'

    def __str__(self):
        return self.nombre
    

carro/views.py
from django.shortcuts import render, redirect
from .carro import Carro
from tienda.models import Producto

# Create your views here.
def agregar_producto(request, producto_id):
    carro = Carro(request)
    producto=Producto.objects.get(id = producto_id)

    carro.agregar(producto=producto)
    return redirect('Tienda')

def eliminar_producto(request, producto_id):
    carro = Carro(request)
    producto=Producto.objects.get(id = producto_id)

    carro.eliminar(producto=producto)
    return redirect('Tienda')

def restar_producto(request, producto_id):
    carro = Carro(request)
    producto=Producto.objects.get(id = producto_id)

    carro.restar_producto(producto=producto)
    return redirect('Tienda')

def limpiar_producto(request):
    carro = Carro(request)
    carro.limpiar_carro()
    return redirect('Tienda')
   

tienda/views.py
from django.shortcuts import render
from tienda.models import Producto, CategoriaProducto
# Create your views here.

def tienda(request):
    productos = Producto.objects.all()
    return render(request, 'tienda/tienda.html', {'productos':productos})

def categoriaProd(request, categoria_id):
    categoriaProducto= CategoriaProducto.objects.get(id=categoria_id)
    productos= Producto.objects.filter(categoriaProducto=categoriaProducto)
    return render(request,'tienda/categoriaProd.html', {'productos':productos, 'categoriaProducto': categoriaProducto})

tienda/templates/carro/widget.html
<table class="table table-bordered">
<thead>

    <tr>
        <th colspan=3 class="alert alert-secondary text-center">
                Carrito de compras
        </th>
    </tr>
    <tr>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Precio</th>
    </tr>
</thead>

<tbody>

    {% if user.is_authenticated%}

        {% if request.session.carro.items %}

            {% for key, value in request.session.carro.items %}

                <tr class="text-center">
                    <th>{{value.nombre}}</th>
                    <th>{{value.cantidad}}</th>
                    <th>
                        <a href="{% url 'carro:agregar' value.producto_id %} " class="btn btn-sm btn-success">+</a>

                        <a href=" {% url 'carro:restar' value.producto_id %} " class="btn btn-sm  btn-danger">-</a>
                        <br>
                        <span style="float:left">$</span> &nbsp &nbsp
                        <span style="float:right">{{value.precio}}</span>

                    </th>
                </tr>

            {% endfor %}
        {% else %}

        <tr>

            <th class="alert alert-danger text-center"  colspan="3">Carrito vacio</th>
            <br>
             {{value.precio}}
    
        </tr>
        {% endif%}

        {% else %}
            <p style="background-color:cadetblue; text-align:center; font-size: large;">Inicia sesion para comprar</p>
    {% endif %}
</tbody>

<tfoot>
    <tr>
        <td colspan="3" class="text-center">
            Total: $ {{importe_total_carro}} M.N.
        </td>
    </tr>
</tfoot>


</table>